//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLink
    {
        public long NLinkId { get; set; }
        public Nullable<int> NformId { get; set; }
        public string Nlink1 { get; set; }
        public Nullable<int> Norder { get; set; }
    
        public virtual NForm NForm { get; set; }
    }
}
