//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public string FileUrl { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
