//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatalogEntities : DbContext
    {
        public CatalogEntities()
            : base("name=CatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<EmailPassword> EmailPasswords { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<hselaggingwaste> hselaggingwastes { get; set; }
        public virtual DbSet<hseleadingindent> hseleadingindents { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<monthly_activity> monthly_activity { get; set; }
        public virtual DbSet<monthly_rob> monthly_rob { get; set; }
        public virtual DbSet<NCategory> NCategories { get; set; }
        public virtual DbSet<NForm> NForms { get; set; }
        public virtual DbSet<NLink> NLinks { get; set; }
        public virtual DbSet<pob> pobs { get; set; }
        public virtual DbSet<ptwinspection> ptwinspections { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<ShoreStaffTraining> ShoreStaffTrainings { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<UserEmail> UserEmails { get; set; }
        public virtual DbSet<UserToShip> UserToShips { get; set; }
        public virtual DbSet<vessel_head> vessel_head { get; set; }
    }
}
