//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailPassword
    {
        public int Id { get; set; }
        public Nullable<int> LoginId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
    }
}
