//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hselaggingwaste
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string warning_m { get; set; }
        public string warning_y { get; set; }
        public string complaints_m { get; set; }
        public string complaints_y { get; set; }
        public string fines_m { get; set; }
        public string fines_y { get; set; }
        public string observations_m { get; set; }
        public string observations_y { get; set; }
        public string injury_m { get; set; }
        public string injury_y { get; set; }
        public string plastic_m { get; set; }
        public string plastic_y { get; set; }
        public string food_m { get; set; }
        public string food_y { get; set; }
        public string cookingoil_m { get; set; }
        public string cookingoil_y { get; set; }
        public string metal_m { get; set; }
        public string metal_y { get; set; }
        public string seweragewater_m { get; set; }
        public string seweragewater_y { get; set; }
        public string hazardous_m { get; set; }
        public string hazardous_y { get; set; }
        public string others_m { get; set; }
        public string others_y { get; set; }
    }
}
