//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hseleadingindent
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string nomeeting_m { get; set; }
        public string nomeeting_y { get; set; }
        public string nosuggestion_m { get; set; }
        public string nosuggestion_y { get; set; }
        public string noemergency_m { get; set; }
        public string noemergency_y { get; set; }
        public string nopermit_m { get; set; }
        public string nopermit_y { get; set; }
        public string notbt_m { get; set; }
        public string notbt_y { get; set; }
        public string nosafetyflashes_m { get; set; }
        public string nosafetyflashes_y { get; set; }
        public string notraining_m { get; set; }
        public string notraining_y { get; set; }
        public string notraininghours_m { get; set; }
        public string notraininghours_y { get; set; }
        public string notrainingpersons_m { get; set; }
        public string notrainingpersons_y { get; set; }
        public string nosafetyflashed_m { get; set; }
        public string nosafetyflashed_y { get; set; }
        public string ltic_m { get; set; }
        public string ltic_y { get; set; }
        public string rwdc_m { get; set; }
        public string rwdc_y { get; set; }
        public string fac_m { get; set; }
        public string fac_y { get; set; }
        public string oi_m { get; set; }
        public string oi_y { get; set; }
        public string pdi_m { get; set; }
        public string pdi_y { get; set; }
        public string ei_m { get; set; }
        public string ei_y { get; set; }
        public string nmi_m { get; set; }
        public string nmi_y { get; set; }
        public string mtc_m { get; set; }
        public string mtc_y { get; set; }
    }
}
