//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_rob
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string openingfuel { get; set; }
        public string openingfreshwater { get; set; }
        public string openingloil { get; set; }
        public string openinghoil { get; set; }
        public string openinggoil { get; set; }
        public string receivedfuel { get; set; }
        public string receivedfreshwater { get; set; }
        public string receivedloil { get; set; }
        public string receivedhoil { get; set; }
        public string receivedgoil { get; set; }
        public string closingfuel { get; set; }
        public string closingfreshwater { get; set; }
        public string closingloil { get; set; }
        public string closinghoil { get; set; }
        public string closinggoil { get; set; }
        public string consumedfuel { get; set; }
        public string consumedfreshwater { get; set; }
        public string consumedloil { get; set; }
        public string consumedhoil { get; set; }
        public string consumedgoil { get; set; }
        public string deliveredfuel { get; set; }
        public string deliveredfreshwater { get; set; }
        public string deliveredloil { get; set; }
        public string deliveredhoil { get; set; }
        public string deliveredgoil { get; set; }
        public string deliveredkfcfuel { get; set; }
        public string deliveredkfcfreshwater { get; set; }
        public string deliveredkfcloil { get; set; }
        public string deliveredkfchoil { get; set; }
        public string deliveredkfcgoil { get; set; }
        public string menginerunninghrsfuel { get; set; }
        public string menginerunninghrsfreshwater { get; set; }
        public string menginerunninghrsloil { get; set; }
        public string menginerunninghrshoil { get; set; }
        public string menginerunninghrsgoil { get; set; }
        public string menginefuelconsfuel { get; set; }
        public string menginefuelconsfreshwater { get; set; }
        public string menginefuelconsloil { get; set; }
        public string menginefuelconshoil { get; set; }
        public string menginefuelconsgoil { get; set; }
        public string aenginerunninghrsfuel { get; set; }
        public string aenginerunninghrsfreshwater { get; set; }
        public string aenginerunninghrsloil { get; set; }
        public string aenginerunninghrshoil { get; set; }
        public string aenginerunninghrsgoil { get; set; }
        public string aenginefuelconsfuel { get; set; }
        public string aenginefuelconsfreshwater { get; set; }
        public string aenginefuelconsloil { get; set; }
        public string aenginefuelconshoil { get; set; }
        public string aenginefuelconsgoil { get; set; }
    }
}
