//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_activity
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string steamingtime { get; set; }
        public string steamingconsumption { get; set; }
        public string steamingmcr { get; set; }
        public string anchoragetime { get; set; }
        public string anchorageconsumption { get; set; }
        public string anchoragemcr { get; set; }
        public string berthtime { get; set; }
        public string berthconsumption { get; set; }
        public string berthmcr { get; set; }
        public string towingtime { get; set; }
        public string towingconsumption { get; set; }
        public string towingmcr { get; set; }
        public string downtime { get; set; }
        public string downconsumption { get; set; }
        public string downmcr { get; set; }
        public string meneauveringtime { get; set; }
        public string meneauveringconsumption { get; set; }
        public string meneauveringmcr { get; set; }
        public string otherstime { get; set; }
        public string othersconsumption { get; set; }
        public string othersmcr { get; set; }
        public string remarkstime { get; set; }
        public string remarksconsumption { get; set; }
        public string remarksmcr { get; set; }
    }
}
