//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pob
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string pobcrew { get; set; }
        public string pobcharterers { get; set; }
        public string pobkfc { get; set; }
        public string pobothers { get; set; }
        public string pobtotal { get; set; }
        public string remarkscrew { get; set; }
        public string remarkscharterers { get; set; }
        public string remarkskfc { get; set; }
        public string remarksothers { get; set; }
    }
}
