//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingID { get; set; }
        public string Training_Topic { get; set; }
        public string Type { get; set; }
        public Nullable<int> Participant_No { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Trainer_Name { get; set; }
        public string Trainer_Desig { get; set; }
        public string Date { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Entered_On { get; set; }
        public Nullable<int> Entered_By { get; set; }
        public string AttendanceSheet { get; set; }
        public string EvaluationSheet { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
