//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vessel_head
    {
        public int id { get; set; }
        public int ShipsId { get; set; }
        public string vessel { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string navigation { get; set; }
        public string imono { get; set; }
        public string manhours { get; set; }
        public string master { get; set; }
        public string chiefofficer { get; set; }
        public string chiefengineer { get; set; }
        public string location { get; set; }
        public Nullable<int> EnteredBY { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
